// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    /// <summary>
    /// Customer credit card information.
    /// </summary>
    [Table("CreditCard", Schema = "Sales")]
    [Index("CardNumber", Name = "AK_CreditCard_CardNumber", IsUnique = true)]
    public partial class CreditCard
    {
        public CreditCard()
        {
            PersonCreditCard = new HashSet<PersonCreditCard>();
            SalesOrderHeader = new HashSet<SalesOrderHeader>();
        }

        /// <summary>
        /// Primary key for CreditCard records.
        /// </summary>
        [Key]
        [Column("CreditCardID")]
        public int CreditCardId { get; set; }
        /// <summary>
        /// Credit card name.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CardType { get; set; }
        /// <summary>
        /// Credit card number.
        /// </summary>
        [Required]
        [StringLength(25)]
        public string CardNumber { get; set; }
        /// <summary>
        /// Credit card expiration month.
        /// </summary>
        public byte ExpMonth { get; set; }
        /// <summary>
        /// Credit card expiration year.
        /// </summary>
        public short ExpYear { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [InverseProperty("CreditCard")]
        public virtual ICollection<PersonCreditCard> PersonCreditCard { get; set; }
        [InverseProperty("CreditCard")]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
    }
}