// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    /// <summary>
    /// Sales representative current information.
    /// </summary>
    [Table("SalesPerson", Schema = "Sales")]
    [Index("Rowguid", Name = "AK_SalesPerson_rowguid", IsUnique = true)]
    public partial class SalesPerson
    {
        public SalesPerson()
        {
            SalesOrderHeader = new HashSet<SalesOrderHeader>();
            SalesPersonQuotaHistory = new HashSet<SalesPersonQuotaHistory>();
            SalesTerritoryHistory = new HashSet<SalesTerritoryHistory>();
            Store = new HashSet<Store>();
        }

        /// <summary>
        /// Primary key for SalesPerson records. Foreign key to Employee.BusinessEntityID
        /// </summary>
        [Key]
        [Column("BusinessEntityID")]
        public int BusinessEntityId { get; set; }
        /// <summary>
        /// Territory currently assigned to. Foreign key to SalesTerritory.SalesTerritoryID.
        /// </summary>
        [Column("TerritoryID")]
        public int? TerritoryId { get; set; }
        /// <summary>
        /// Projected yearly sales.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? SalesQuota { get; set; }
        /// <summary>
        /// Bonus due if quota is met.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal Bonus { get; set; }
        /// <summary>
        /// Commision percent received per sale.
        /// </summary>
        [Column(TypeName = "smallmoney")]
        public decimal CommissionPct { get; set; }
        /// <summary>
        /// Sales total year to date.
        /// </summary>
        [Column("SalesYTD", TypeName = "money")]
        public decimal SalesYtd { get; set; }
        /// <summary>
        /// Sales total of previous year.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal SalesLastYear { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        [Column("rowguid")]
        public Guid Rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey("BusinessEntityId")]
        [InverseProperty("SalesPerson")]
        public virtual Employee BusinessEntity { get; set; }
        [ForeignKey("TerritoryId")]
        [InverseProperty("SalesPerson")]
        public virtual SalesTerritory Territory { get; set; }
        [InverseProperty("SalesPerson")]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
        [InverseProperty("BusinessEntity")]
        public virtual ICollection<SalesPersonQuotaHistory> SalesPersonQuotaHistory { get; set; }
        [InverseProperty("BusinessEntity")]
        public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistory { get; set; }
        [InverseProperty("SalesPerson")]
        public virtual ICollection<Store> Store { get; set; }
    }
}